[project]
name = "ppo"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "gymnasium[classic-control,other]>=0.29.0",
    "ipykernel>=7.3.0",
    "stable-baselines3>=2.0.0",
    "tensorboard>=2.14.0",
    "torch>=2.0.0",
    "tyro>=0.8.0",
    "wandb>=0.15.0",
]

[tool.uv]
package = false
